dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('dogs/<int:dog_id>/add_photo/', views.add_photo, name='add_photo'),
    path('dogs/<int:dog_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

    

  

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

class Toy(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
      return self.name

  def get_absolute_url(self):
      return reverse('toys_detail', kwargs={'pk': self.id})
   

class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'dog_id': self.id})
    
    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >= len(MEALS)

class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for dog_id: {self.dog_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import FeedingForm
import uuid
import boto3
from .models import Dog, Toy, Photo


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def dogs_index(request):
    dogs = Dog.objects.filter(user=request.user)
    return render(request, 'dogs/index.html', { 'dogs': dogs })

@login_required
def dogs_detail(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    toys_dog_doesnt_have = Toy.objects.exclude(id__in = dog.toys.all().values_list('id'))
    feeding_form = FeedingForm()
    return render(request, 'dogs/detail.html', { 
        'dog': dog, 
        'feeding_form': feeding_form,
        'toys': toys_dog_doesnt_have 
    })

@login_required
def add_feeding(request, dog_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.dog_id = dog_id
        new_feeding.save()
    return redirect('detail', dog_id=dog_id)

@login_required
def assoc_toy(request, dog_id, toy_id):
    Dog.objects.get(id=dog_id).toys.add(toy_id)
    return redirect('detail', dog_id=dog_id)

@login_required
def add_photo(request, dog_id):
    S3_BASE_URL ='https://s3-us-east-2.amazonaws.com/'
    BUCKET = 'dogcollection.ssk'
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, dog_id=dog_id)
            photo.save()
        except:
            print('An error has occurred uploading file to S3')
    return redirect('detail', dog_id=dog_id)
    
def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


class DogCreate(LoginRequiredMixin, CreateView):
    model = Dog
    fields = ['name', 'breed', 'description', 'age']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DogUpdate(LoginRequiredMixin, UpdateView):
    model = Dog
    fields = ['breed', 'description', 'age']

class DogDelete(LoginRequiredMixin, DeleteView):
    model = Dog
    success_url = '/dogs/'

# CRUD for Toy model
class ToyList(LoginRequiredMixin, ListView):
    model = Toy

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = ['name', 'color']

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Doggie Deck</h1>
    <hr />
    <p>Here you will have an opportunity to showcase all your dogs in one page with their name, unique description, breed, and age. You can also do the following:
        <ul>
            <li>Track their meals</li>
            <li>Feed them breakfast, lunch, or dinner</li>
            <li>Track their toys</li>
            <li>Assign them toys</li>
        </ul>
    </p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Doggie Deck</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Doggie Deck</a></li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'toys_create' %}">Add Toy</a></li>
              <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
              <li><a href="{% url 'dogs_create' %}">Add Dog</a></li>
              <li><a href="{% url 'index' %}">View All Dogs</a></li>
              <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'signup' %}">Sign Up</a></li>
              <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">
      {% block content %}
      {% endblock %}
    </main>
    <footer class="page-footer">
      <div class="right">All Rights Reserved, &copy; Salma Khan 2019 &nbsp;</div>
    </footer>
  </body>
  </html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Details of the Dog</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
          <div class="card-content">
              <span class="card-title">{{ dog.name }}</span>
              <p>Breed: {{ dog.breed }}</p>
              <p>Description: {{ dog.description }}</p>
              {% if dog.age > 0 %}
                  <p>Age: {{ dog.age }}</p>
              {% else %}
                  <p>Age: Puppy</p>
              {% endif %}
          </div>
          <div class="card-action">
              <a href="{% url 'dogs_update' dog.id %}">Edit</a>
              <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
          </div>
        </div>
        {% for photo in dog.photo_set.all %}
          <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
          <div class="card-panel teal-text center-align">No Photos Uploaded Yet</div>
        {% endfor %}
        <form action="{% url 'add_photo' dog.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
          {% csrf_token %}
          <input type="file" name="photo-file">
          <br><br>
          <input type="submit" class="btn" value="Upload Photo">
      </form>
    </div>

    <div class="col s6">
        <form action="{% url 'add_feeding' dog.id %}" method="POST">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" class="btn" value="Add Feeding">
        </form>
        <br>
        {% if dog.fed_for_today %}
            <div class="card-panel teal-text center-align">{{dog.name}} has been fed all meals for today!</div>
        {% else %}
            <div class="card-panel red-text center-align">{{dog.name}} might be hungry now!</div>
        {% endif %}
        <table class="striped">
            <thead>
                <tr><th>Date</th><th>Meal</th></tr>
            </thead>
            <tbody>
                {% for feeding in dog.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ dog.name }}'s Toys</h3>
    {% if dog.toys.count %}
      {% for toy in dog.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys Yet :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' dog.id toy.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{dog.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>

<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    var selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>List of Dogs</h1>

{% for dog in dogs %}
    <div class="card">
        <a href="{% url 'detail' dog.id %}"> 
            <div class="card-content">
                <span class="card-title">{{ dog.name }}</span>
                <p>Breed: {{ dog.breed }}</p>
                <p>Description: {{ dog.description }}</p>
                {% if dog.age > 0 %}
                    <p>Age: {{ dog.age }} </p>
                {% else %}
                    <p>Age: Puppy</p>
                {% endif %}
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Hello Dog Lover, Welcome!</h1>
<p>Please Login to have full access to the Doggie Deck and all its functionalities!</p>


{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Dog</h1>
<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes_Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add a New Dog</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Toy</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Details of The Toy</h1>

<div class="row">
    <div class="col s6 col-offset-3">
        <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
        <div class="card-action">
            <a href="{% url 'toys_update' toy.id %}">Edit</a>
            <a href="{% url 'toys_delete' toy.id %}">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add a New Toy</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>List of Toys</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}